"""
Career Readiness Engine.

Readiness is explicitly NOT a job-placement prediction. It is a transparent,
deterministic measure of demonstrated skill coverage against a selected role,
combining five weighted components. All numbers are derived from the
database (StudentProgress, AssessmentAttempt, Evidence) - nothing here is
generated by an LLM.
"""
from sqlalchemy.orm import Session

from .. import models
from .gap_engine import run_gap_analysis

WEIGHTS = {
    "technical_skills": 0.30,
    "project_evidence": 0.20,
    "assessment_performance": 0.20,
    "skill_coverage": 0.20,
    "verification": 0.10,
}


def compute_readiness(db: Session, user_id: str, career_id: str, save_snapshot: bool = True) -> dict:
    analysis = run_gap_analysis(db, user_id, career_id)
    career_skill_ids = [g["skill"].id for g in analysis["gaps"]]

    progress_rows = (
        db.query(models.StudentProgress)
        .filter(models.StudentProgress.user_id == user_id, models.StudentProgress.skill_id.in_(career_skill_ids))
        .all()
    ) if career_skill_ids else []

    # Technical skills: average current level vs required, capped at 100
    if analysis["gaps"]:
        tech_scores = [
            min(100, (g["current_level"] / g["required_level"]) * 100) if g["required_level"] else 100
            for g in analysis["gaps"]
        ]
        technical_skills = round(sum(tech_scores) / len(tech_scores), 1)
    else:
        technical_skills = 0.0

    # Project evidence: fraction of relevant skills backed by project evidence
    if career_skill_ids:
        with_project = sum(1 for p in progress_rows if p.has_project_evidence)
        project_evidence = round((with_project / len(career_skill_ids)) * 100, 1)
    else:
        project_evidence = 0.0

    # Assessment performance: average best-percent across relevant skills that have attempts
    attempted = [p.best_assessment_percent for p in progress_rows if p.best_assessment_percent is not None]
    assessment_performance = round(sum(attempted) / len(attempted), 1) if attempted else 0.0

    skill_coverage = analysis["skill_coverage"]

    # Verification: fraction of relevant skills marked "verified"
    if career_skill_ids:
        verified = sum(1 for p in progress_rows if p.status == "verified")
        verification = round((verified / len(career_skill_ids)) * 100, 1)
    else:
        verification = 0.0

    overall = round(
        technical_skills * WEIGHTS["technical_skills"]
        + project_evidence * WEIGHTS["project_evidence"]
        + assessment_performance * WEIGHTS["assessment_performance"]
        + skill_coverage * WEIGHTS["skill_coverage"]
        + verification * WEIGHTS["verification"],
        1,
    )

    highest = max([
        ("technical skills", technical_skills),
        ("project evidence", project_evidence),
        ("assessment performance", assessment_performance),
        ("verified skills", verification)
    ], key=lambda x: x[1])

    lowest = min([
        ("technical skills", technical_skills),
        ("project evidence", project_evidence),
        ("assessment performance", assessment_performance),
        ("verified skills", verification)
    ], key=lambda x: x[1])

    if overall < 30:
        summary = f"Your readiness is low. While your {highest[0]} is your strongest area ({highest[1]}%), you lack {lowest[0]} ({lowest[1]}%)."
    elif overall < 70:
        summary = f"You are on the right track! Your {highest[0]} is solid ({highest[1]}%), but you lack {lowest[0]} ({lowest[1]}%). Focus on improving that to increase your readiness."
    else:
        summary = f"You are highly ready! You have strong {highest[0]} ({highest[1]}%). To reach 100%, continue polishing your {lowest[0]}."

    explanation = {
        "summary": summary,
        "technical_skills": f"Average of your current skill levels relative to each required "
                             f"level for {analysis['career'].name} (weight {int(WEIGHTS['technical_skills']*100)}%).",
        "project_evidence": f"Share of required skills backed by at least one project "
                             f"(weight {int(WEIGHTS['project_evidence']*100)}%).",
        "assessment_performance": f"Average score across assessments you've completed for "
                                   f"relevant skills (weight {int(WEIGHTS['assessment_performance']*100)}%).",
        "skill_coverage": f"How much of the required skill set you currently cover, capped per-skill "
                           f"at the required level (weight {int(WEIGHTS['skill_coverage']*100)}%).",
        "verification": f"Share of required skills that have reached full Verified status "
                         f"(weight {int(WEIGHTS['verification']*100)}%).",
    }

    result = {
        "overall_readiness": overall,
        "technical_skills": technical_skills,
        "project_evidence": project_evidence,
        "assessment_performance": assessment_performance,
        "skill_coverage": skill_coverage,
        "verification": verification,
        "explanation": explanation,
    }

    if save_snapshot:
        snapshot = models.ReadinessSnapshot(
            user_id=user_id,
            career_id=career_id,
            overall_readiness=overall,
            technical_skills=technical_skills,
            project_evidence=project_evidence,
            assessment_performance=assessment_performance,
            skill_coverage=skill_coverage,
            verification=verification,
        )
        db.add(snapshot)
        db.commit()

    return result
